on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  BPF_LINKER_VERSION: "v0.9.13"

name: CI
jobs:
  lint:
    name: Lint
    runs-on: codeberg-small
    container:
      image: node:25-trixie
    steps:
      - uses: https://github.com/actions/checkout@v6
      - uses: https://github.com/dtolnay/rust-toolchain@stable

      # make sure all code has been formatted with rustfmt
      - name: check rustfmt
        run: |
          rustup component add rustfmt
          cargo fmt -- --check --color always

      # run clippy to verify we have no warnings
      - run: cargo fetch --target x86_64-unknown-linux-gnu
      - name: cargo clippy
        run: |
          rustup component add clippy
          cargo clippy --all-targets --all-features -- -D warnings

  test:
    runs-on: codeberg-small
    container:
      image: node:25-trixie
    steps:
      - uses: https://github.com/actions/checkout@v6
      - uses: https://github.com/dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: rust-src
      - name: build eBPF
        run: |
          (cd /usr/bin && curl -L https://github.com/aya-rs/bpf-linker/releases/download/${BPF_LINKER_VERSION}/bpf-linker-x86_64-unknown-linux-gnu.tar.gz | tar xzf - bpf-linker)
          ./build_ebpf.sh
      - run: cargo fetch --target x86_64-unknown-linux-gnu
      - name: cargo test build
        run: cargo build --tests -p xdp -p tests
      - name: cargo test
        run: cargo test -p xdp -p tests

  miri-test:
    runs-on: codeberg-medium
    container:
      image: node:25-trixie
    steps:
      - uses: https://github.com/actions/checkout@v6
      - uses: https://github.com/dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: rust-src, miri
      - run: cargo fetch --target x86_64-unknown-linux-gnu
      - name: build eBPF
        run: |
          (cd /usr/bin && curl -L https://github.com/aya-rs/bpf-linker/releases/download/${BPF_LINKER_VERSION}/bpf-linker-x86_64-unknown-linux-gnu.tar.gz | tar xzf - bpf-linker)
          ./build_ebpf.sh
      - name: install nextest
        run: curl -LsSf https://get.nexte.st/latest/linux-musl | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin
      - name: cargo test build
        run: cargo build --tests
      - name: cargo test
        run: cargo nextest run
      - name: cargo miri test
        run: cargo miri nextest run -j 4

  integ-test:
    # Disable for now, unfortunately the codeberg hosted runners don't allow
    # manipulation of network namespaces
    if: false
    runs-on: codeberg-medium
    container:
      image: node:25-trixie
    steps:
      - uses: https://github.com/actions/checkout@v6
      - uses: https://github.com/dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: rust-src
      - run:
          # need the ip command
          apt-get update && apt-get install iproute2 -y
      - run: cargo fetch
      - name: build eBPF
        run: |
          (cd /usr/bin && curl -L https://github.com/aya-rs/bpf-linker/releases/download/${BPF_LINKER_VERSION}/bpf-linker-x86_64-unknown-linux-gnu.tar.gz | tar xzf - bpf-linker)
          ./build_ebpf.sh
      - name: cargo test build
        working-directory: ./crates/integ
        run: cargo build --tests
      - name: cargo test
        working-directory: ./crates/integ
        run: cargo test

  docs:
    runs-on: codeberg-small
    container:
      image: node:25-trixie
    env:
      RUSTDOCFLAGS: "-D warnings"
    steps:
      - uses: https://github.com/actions/checkout@v6
      - uses: https://github.com/dtolnay/rust-toolchain@stable
      - run: cargo fetch
      - name: cargo doc check
        run: cargo doc

  deny-check:
    name: cargo-deny
    runs-on: codeberg-small
    container:
      image: node:25-trixie
    steps:
      - uses: https://github.com/actions/checkout@v6
      - uses: https://github.com/EmbarkStudios/cargo-deny-action@v2

  publish-check:
    name: Publish Check
    runs-on: codeberg-small
    container:
      image: node:25-trixie
    steps:
      - uses: https://github.com/actions/checkout@v6
      - uses: https://github.com/dtolnay/rust-toolchain@stable
      - run: cargo fetch
      - name: cargo publish check
        run: cargo publish --dry-run

  test_success:
    runs-on: codeberg-tiny
    container:
      image: node:25-trixie
    needs: [lint, test, miri-test, docs, publish-check]
    steps:
      - run: echo "All test jobs passed"
